<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengeDay12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1
The following arrays are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```


Calculate arithmetic means of these arrays (elementwise) and print result to the console.

Expected result:
```
[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]
```






In [ ]:
import numpy as np

A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

np.mean([A,B], axis=0)

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

Exercise 2
The following arrays are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```


Multiply these arrays (elementwise) and print result to the console.

Expected result:

```
[[12 12 18 10]
 [30  9  2 30]]
```



In [ ]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

np.multiply(A, B)

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

Exercise 3
The following array is given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```



Calculate the square root of each element of this array and print result to the console.

Expected result:
```
[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]
```



In [ ]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

np.sqrt(A)

array([[1.73205081, 2.        , 3.        , 1.41421356],
       [2.23606798, 1.73205081, 1.41421356, 2.23606798]])