<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengeDay8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1
The following array is given:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



Transform this array into the following:


```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```




In response, print transformed array to the console.








In [ ]:
array =([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

import numpy as np
flipped_array = np.flip(array, axis=1)
flipped_array


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

# Exercise 2
The following  array is given:




```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



Transform this array into the following:

```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```

In response, print transformed array to the console.

In [ ]:
array = ([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

flipped_array = np.flip(array, axis=(0,1))
flipped_array

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

# Exercise 3
Random seed is set to 42. The following array is given:

```
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)
```



Extract the first channel (index 0) of this image array and print it to the console.



```
Expected output:

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13][ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]
```



In [ ]:
np.random.seed = 42

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

image[:, :, 0]
# np.extract(image, image[:, :, 0])

array([[ 72, 173, 162,  50, 151,  72,  54, 123,  70, 118],
       [214, 139,  27,  24,  89, 169, 146,  92, 188,  70],
       [178,  94,  48, 246, 152, 165, 246, 117,   5,  88],
       [ 18, 145, 170, 112, 200,  40, 196,  87, 172, 193],
       [131, 171, 149,  24, 247, 141,  93, 182, 250,  49],
       [170,  15, 119,  59, 126,  86, 219,  62,  70, 102],
       [157, 199, 207, 253, 224, 179,  79,  95, 178, 135],
       [  2, 255, 225, 158,  78,   8, 155, 201, 134,  20],
       [ 85, 158, 154,  43, 228,  83, 100,  86, 124, 176],
       [ 38, 189, 166, 158, 164,  34, 113, 132,  22, 234]], dtype=uint8)

# Exercise 4
The following array is given:

```
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)
```



Extract any array of shape (5, 5, 3) from this array and assign to the result variable.

In [ ]:
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

subimage = image[:5, :5, :3]
print(subimage.shape)
print(subimage)




(5, 5, 3)
[[[206  52 200]
  [144 242  14]
  [  8   3 148]
  [ 16  42 112]
  [100 153 254]]

 [[189 213 104]
  [169  22 254]
  [117  58  38]
  [ 59  80 122]
  [115  10  96]]

 [[136 144 207]
  [249   1 197]
  [218  28 176]
  [182  83 158]
  [235 238 121]]

 [[ 93  15 205]
  [145  31  81]
  [179 197 244]
  [211 125  47]
  [  5  53  54]]

 [[118 164 175]
  [ 56  20 242]
  [ 90  46  64]
  [ 67 241 203]
  [169  75 153]]]
