<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengeDay13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1
The following arrays are given:

```
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
```



Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array.

In response, print result to the console.

Expected result:
```True```





In [ ]:
import numpy as np

np. set_printoptions(precision=50)
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

C = np.round(np.sin(A)**2+np.cos(A)**2, 10)

np.array_equal(B, C)


True

# Exercise 2
The following arrays are given:

```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```



Shapes of these arrays:

A - 3x2

B - 2x3

Perform matrix multiplication A x B and print result to the console.

Expected result:

```
[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]
```



In [ ]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])

np.matmul(A, B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

# Exercise 3
The following array is given:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```



Calculate the determinant of this matrix and print it to the console.

Expected result:
`51.999999999999986`

In [ ]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

np.linalg.det(A)

51.999999999999986