<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengeDay16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ChallengesDay16


Exercise 1
Calculate the roots of the following polynomials:

```
Q(x) = 2*x**3 + 4*x**2 - 5*x + 1
R(x) = 2*x**3 - 5*x + 1
```



In response print these roots to the console as shown below.

Expected output:

```
[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]
```







In [ ]:
import numpy as np

Q = [2, 4, -5, 1]
R = [2, 0, -5, 1]

print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


Exercise 2
The following polynomials are given:

```
W(x) = 4*x**2 + 5*x + 1

Q(x) = 2*x**3 + 4*x**2 - 5*x + 1
```


Perform the following operations and print results to the console as shown below:

W(x) + Q(x)

W(x) - Q(x)

W(x) * Q(x)

W(x) + 2*Q(x)
Expected output:

```
[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]
```



In [ ]:
#Не уверен, как ты вывела такой результат (без нескольких кривых трансформаций)

from numpy.polynomial import polynomial as P
from numpy.polynomial import Polynomial

W = Polynomial([1, 5, 4])
Q = Polynomial([1, -5, 4, 2])

print(P.polyadd(W, Q))
print(P.polysub(W, Q))
print(P.polymul(W, Q))
print(P.polyadd(W, 2*Q))

[Polynomial([2., 0., 8., 2.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')]
[Polynomial([ 0., 10.,  0., -2.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')]
[Polynomial([  1.,   0., -17.,   2.,  26.,   8.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')]
[Polynomial([ 3., -5., 12.,  4.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')]


Exercise 3
The following array is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```



Use the sign function for this array.

Reminder: The sign function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

Expected result:

```
[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]
```



In [ ]:
import numpy as np

A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]
