<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengesDay2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1
The following array:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```



transform to the following:

```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```



In response, print transformed array to the console.

Expected output:

```
[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]
```




In [ ]:
import numpy as np

array = np.zeros([6,6], dtype=int)
# odd column odd row
# odd column even row
array[::2, ::2]=10
array[1::2, ::2]=5
array

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

# Exercise 2
Combine the following arrays into one as shown below and print it to the console.


```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```


Expected result:

```
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]
```




In [ ]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

print(np.concatenate((A, B)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


# Exercise 3
The following arrays are given:

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])
```

   

Extract the same elements (intersection) of the arrays as a list and print result to the console.

Expected result:
[0 2 3]

In [ ]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])

# print(A)
# print(B)

#Просился list, тут ndarray
intersection = np.intersect1d(A,B)
print("{} type: {}".format(intersection, type(intersection)))


#можно конвертнуть
intersection = list(intersection)
print("{} type: {}".format(intersection, type(intersection)))


[0 2 3] type: <class 'numpy.ndarray'>
[0, 2, 3] type: <class 'list'>
