<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengesDay15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1

The following array is given:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```

Starting with the second row of this array, randomly shuffle the rows and print result to the console.

Expected output:
```
[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']
 ['004' '2.49']]
```



In [8]:
import numpy as np
import pandas as pd

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:, :])
print(A)

[['id' 'price']
 ['005' '1.49']
 ['001' '14.99']
 ['003' '7.99']
 ['004' '2.49']
 ['002' '4.99']]


# Exercise 2

The following array is given:

`A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])`
Return a list of indexes that sorts this array in ascending order and print it to the console.

Expected result:

`[5 2 1 0 4 3]`

In [11]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

print(np.argsort(A))

[5 2 1 0 4 3]


# Exercise 3
The following array is given:

`A = np.random.randn(10, 8)`
Round the values of this array to three decimal places and print result to the console.
Expected output:

```
[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]
```

In [15]:
np.set_printoptions(suppress=True)

A = np.random.randn(10, 8)
# print(A)

A_rounded = np.round(A, 3)
print(A_rounded)

[[-0.012  0.288  1.162 -0.983  0.545 -1.552 -1.577 -1.344]
 [ 1.132 -1.092  0.3    0.136 -1.323  0.937  1.98  -0.731]
 [ 2.243 -2.431  0.676 -0.417 -0.112  0.167 -0.376  1.578]
 [ 0.896 -0.614  0.896 -0.716  1.605  1.403 -0.865 -0.01 ]
 [ 1.741  0.596 -0.107  0.44   0.437 -0.108  0.239 -0.689]
 [ 0.656 -1.437 -0.85  -0.714 -0.033 -0.639 -0.184  0.328]
 [-1.131  2.125  0.586 -2.283  0.873 -0.305  0.581 -1.17 ]
 [-0.228  0.241  0.964  0.955  0.926 -0.661 -1.004 -0.166]
 [-0.039 -1.116  0.937  0.432 -0.656  1.401 -0.976 -0.803]
 [-1.13  -0.084 -0.716  2.327  0.843 -1.723 -0.033  0.838]]


# Exercise 4
Calculate  the roots of the following polynomial:

`W(x) = 4 * x**2 + 5 * x + 1`

In response, print these roots to the console.

Expected result:
`[-1.   -0.25]`

In [20]:
print(np.roots([4, 5, 1]))

[-1.   -0.25]
