<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengesDay10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ChallengesDay10

# Exercise 1
The following two-dimensional array is given:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```



Split this array into three parts:

*the first two columns assign to the A1 variable

*the next four columns assign to the A2 variable

*the last two columns assign to the A3 variable

In response, print these arrays to the console as shown below.

Expected result:

```
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
```








In [ ]:
import numpy as np

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A

B, C, D = np.split(A, indices_or_sections=[2,6], axis=1)

print(B)
print(C)
print(D)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 3 5 0]
 [5 0 3 6]
 [6 0 2 2]
 [1 5 4 4]
 [3 3 3 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# Exercise 2
The following array is given:

`A = np.random.randint(low=0, high=2, size=(10, 6))`

Calculate the total number of non-zero elements in this array and print it to the console.

Expected result:
`31`

In [ ]:
A = np.random.randint(low=0, high=2, size=(10, 6))

np.count_nonzero(A)

31

# Exercise 3
The following array is given below:

```
np.random.seed(42)
A = np.random.randn(10, 4)
```



Set the Numpy option to print arrays with specified precision. Set precision to 4 and print this array.


Expected output:

```
[[-1.151   0.3757 -0.6006 -0.2917]
 [-0.6017  1.8523 -0.0135 -1.0577]
 [ 0.8225 -1.2208  0.2089 -1.9597]
 [-1.3282  0.1969  0.7385  0.1714]
 [-0.1156 -0.3011 -1.4785 -0.7198]
 [-0.4606  1.0571  0.3436 -1.763 ]
 [ 0.3241 -0.3851 -0.6769  0.6117]
 [ 1.031   0.9313 -0.8392 -0.3092]
 [ 0.3313  0.9755 -0.4792 -0.1857]
 [-1.1063 -1.1962  0.8125  1.3562]]
```



In [ ]:
np.random.seed(42)
A = np.random.randn(10, 4)

np.set_printoptions(precision=4)
A

array([[ 0.4967, -0.1383,  0.6477,  1.523 ],
       [-0.2342, -0.2341,  1.5792,  0.7674],
       [-0.4695,  0.5426, -0.4634, -0.4657],
       [ 0.242 , -1.9133, -1.7249, -0.5623],
       [-1.0128,  0.3142, -0.908 , -1.4123],
       [ 1.4656, -0.2258,  0.0675, -1.4247],
       [-0.5444,  0.1109, -1.151 ,  0.3757],
       [-0.6006, -0.2917, -0.6017,  1.8523],
       [-0.0135, -1.0577,  0.8225, -1.2208],
       [ 0.2089, -1.9597, -1.3282,  0.1969]])

# Exercise 4
The following array is given:

`A = np.array([1.2e-6, 1.7e-7])`

Set the precision to 8 and also set the appropriate Numpy option to suppress mathematical notation and print this array to the console.


Expected result:
`[0.0000012  0.00000017]`

In [ ]:
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(precision=8, suppress=True)
print(A)

[0.0000012  0.00000017]
