<a href="https://colab.research.google.com/github/velkir/ChallengesDayN/blob/main/ChallengeDay11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1
The following array is given:

```
np.random.seed(42)
A = np.random.randn(8, 4)
```

Remove the third column and print this array to the console.


Expected result:

```
[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]
```



In [ ]:
import numpy as np

np.random.seed(42)
A = np.random.randn(8, 4)

A = np.delete(A, obj=3, axis=1)
A

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [-0.23415337, -0.23413696,  1.57921282],
       [-0.46947439,  0.54256004, -0.46341769],
       [ 0.24196227, -1.91328024, -1.72491783],
       [-1.01283112,  0.31424733, -0.90802408],
       [ 1.46564877, -0.2257763 ,  0.0675282 ],
       [-0.54438272,  0.11092259, -1.15099358],
       [-0.60063869, -0.29169375, -0.60170661]])

# Exercise 2
A one-dimensional array v (vector) is given:

`v = np.array([3, 4, -2])`

Calculate the norm of this vector and print result to the console.

In [ ]:
v = np.array([3, 4, -2])

np.linalg.norm(v)
# Этот вариант попонятнее
# np.linalg.norm(v, 1)


9.0

# Exercise 3
The following array is given:

```
np.random.seed(42)
A = np.random.randint(10, size=(100, 30))
```

Set the Numpy option to print only ten edge elements and then print this array to the console.

In [ ]:
np.random.seed(42)
A = np.random.randint(10, size=(100, 30))

np.set_printoptions(edgeitems=10)
print(A)

[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]
